### ISSUE TITLE
Isla de Lobos not downloaded

### ISSUE THREAD

**Issue by Virtakuono** [mapsme/omim#1003]
For some reason the data on Isla de Lobos is not downloaded when downloading the Uruguay data.

**Comment by deathbaba** [comment]
Thanks! We’ll take a look. @Zverik

**Comment by Zverik** [comment]
I don't understand which island do you mean. Could you please share its coordinates?
![isla_lobos](https://cloud.githubusercontent.com/assets/766031/11818004/e28519b8-a368-11e5-9f2a-a9ad78cb1208.png)

**Comment by Virtakuono** [comment]
https://www.openstreetmap.org/#map=16/-35.0265/-54.8836 This island. The island itself shows on the phone screen, but when I try to search for it, I get nothing (For comparison, searching for Isla Gorriti nearby gives a valid result). Also, the name of the island does not show on the map, and neither do the buildings nor the beach at the northern end of the island.

**Comment by Zverik** [comment]
You are right, this island wasn't included in the bounding polygon for Uruguay. It won't be in the next release, which is this week (since we've already started creating maps for it). But starting this Thursday, you can use Uruguay.mwm from an unofficial [daily updated map repository](http://www.openstreetmap.org/user/Zverik/diary/35658): I've put the fixed polygon there.

**Comment by Virtakuono** [comment]
Thanks! Kudos for the fast resolution.

**Comment by utack** [comment]
Can this be closed?
