### ISSUE TITLE
browser  / web version

### ISSUE THREAD

**Issue by Rik44444** [mapsme/omim#10348]
hi maps.me,
great work !! love the app. I'm posting this to say that a feature i'd quite often like to use, but cannot, is to look 1) a location or 2) a route up online behind my computer, and then later access it on my phone. it'd be really convenient if the location or route could be sent to my maps.me app on my phone from the browser, as is for example possible with TomTom devices. 
are you considering to launch a maps.me browser version or to build a plugin for openstreetmaps.org so this becomes possible?
best.
Rik

**Comment by thany** [comment]
How about using [OSM](https://openstreetmap.org/) directly?

**Comment by ForkWithMe** [comment]
Hi,

Thanks for your feedback <3

Please check our web version at https://routes.maps.me/webeditor/ 

The web version is in early development stage, for example, it uses OSM map layer instead of our own, consider it as a beta or even an alpha version. Originally, it was designed for creating and publishing of travel guides. You can mark locations and connect them with a straight line, then save it and share a link to your route. 

We also plan to add possibility to create routes via the web version in the future.

**Comment by thany** [comment]
Please don't delete my comment if you don't agree. You're being very uncool.

**Comment by Rik44444** [comment]
hi great thanks, it looks great, just made a login, will check it out. Already a suggestion: creating routes in the future would be awesome, but also some link between the web page and the app on your phone would be amazing. TomTom does this, that you can send locations and routes to your phone. Saves tons of time!
