### ISSUE TITLE
The open source code is free, for a paid app?

### ISSUE THREAD

**Issue by FelixINX** [mapsme/omim#106]
Hi,

I have buy this app, but is the following code, the official code for the pro app?

Thanks!

**Comment by therearesomewhocallmetim** [comment]
Hi!

There has been no pro version for some time now, since we made the application free for the users. The current free version has the full functionality, e.g. it is what used to be a pro version. And yes, this is the official code for it.

You can mark this issue as closed if this answers your question.

Best regards,
Timofey

**Comment by FelixINX** [comment]
Ok, thanks!
