### ISSUE TITLE
Map rename request: Netherlands Antilles

### ISSUE THREAD

**Issue by milovanderlinden** [mapsme/omim#10951]
Hello,

I am a long time OpenStreetMapper training young adults to contribute to OpenStreetMap.

In Maps.me, one of the maps in the Caribbean is called "Netherlands Antilles", however: Aruba and Curacao are independent countries since 2010. Would it be possible to split the maps for Aruba and Curacao out of "The Netherlands Antilles"? If required, I can help.

**Comment by tatiana-yan** [comment]
We can leave it as a single part of the map but change the name of this map to the correct list of countries names. Is it ok?

**Comment by milovanderlinden** [comment]
That would be great!

**Comment by tatiana-yan** [comment]
https://jira.mail.ru/browse/MAPSME-10667 we are expecting to fix it in maps.me 9.2 (next major release).

**Comment by thany** [comment]
Please note the Antilles are indeed indepedent countries, but stilll also a constituent part of the Kingdom of the Netherlands. So listing "Netherlands Antilles" is not incorrect, the incorrect part is listing is as a _country_.

**Comment by tatiana-yan** [comment]
If something is listed in the map name it does not mean it's a separate country. It only means it's inside this part of the map. If there is no "Netherlands Antilles" with place=country in osm we do not have country object for it in our maps.

**Comment by milovanderlinden** [comment]
That is an interesting statement @thany that is not without controversy.

I did not say it was incorrect I am addressing this from a *user perspective*. Imagine yourself or a person from the USA booking a holiday to Curacao, Bonaire or Aruba. The coverage on these islands by Google Maps is low. So you step out of the plane and look for the best offline map alternative. In comes "maps.me"; you download it from the play store and start looking for the map of the place you are visiting. It is not there.

Outside of the kingdom of the Netherlands, almost nobody is familiar with the constituent in day to day life, people on the islands identify with the name of the island. Less and less people identify with the "Kingdom of the Netherlands" and even Dutch as a language is losing ground. The constituent is not advertising itself in the tourism industry, the individual islands are. The islands are hardly interconnected. To travel from Curacao to Aruba, you can take a plane maybe 4 times a week at most; it is impossible to generate a route from one of the islands to the other, be it on Google Maps or Maps.me.

In my opinion the use case to have "Netherlands Antilles" listed and not Aruba, Curacao and Bonaire is extremely weak.

**Comment by milovanderlinden** [comment]
> We can leave it as a single part of the map but change the name of this map to the correct list of countries names ("Aruba, Curacao, Caribbean Netherlands" or so).

Please do that as the acceptable solution to my question. Thanks again @tatiana-yan !

**Comment by thany** [comment]
@milovanderlinden I wasn't trying to defend the current state where Antilles is listed as is. I was only saying that it is technically correct. I totally agree with you: people living on an island, regardles of whether that island is an independent state, a souvereign region, a province, a city state, or otherwise, people living there do indeed identify as islanders (to pick a generic term).

This problem might be even more sensetive for Sint Maarten / Saint Martin, where the whole island belongs to two countries (The Netherlands and France) but the islanders identify as neither. Also goes for the British Overseas Territories, where the peoples likely do not identify as being British.

And I guess in times of ambiguity, call regions by how people identify with it. Hong Kong would be a modern-day example of this - the people there identify as Hong Kongese first, Chinese second. Although it can be challenging to keep track of every such change, and also keep everyone happy when there's political tension.

Fortunately, back to the issue at hand, it's a simple and pretty obvious change to make :)
