### ISSUE TITLE
Wrong settlement names

### ISSUE THREAD

**Issue by VMironiuk** [mapsme/omim#11119]
Hi,
in some cases I've got wrong settlement names in the list of search results. It mostly happens when I search some objects in villages.
For example, for a query _центральна 81 вишеньки_ I get results as on screenshots:

![2019-06-25 15 07 43](https://user-images.githubusercontent.com/11456154/60097710-9db23c80-975c-11e9-814f-2b295770a7ee.jpg)

![2019-06-25 15 07 24](https://user-images.githubusercontent.com/11456154/60097719-a60a7780-975c-11e9-9bbf-76ebdbb50bf1.jpg)

**OS:** iOS 12.3.1
**MAPS.ME Version:** 9.1.7.0
**Coordinates to check:** 50.30489,30.71800

**Comment by tatiana-yan** [comment]
Hello.
Thank you for report.
We use heuristics and rough city boundaries to determine settlement names. Sometimes we underestimate villages.
It happens because different countries are mapped in different way. It's common practice to map city districts as villages. For Example:

![IMAGE 2019-06-25 16:04:32](https://user-images.githubusercontent.com/9213190/60100685-ebca3e80-9762-11e9-89ea-036bf86718cd.jpg)

we try to prevent determing location as Senen/Kebon Sirih/Tahan/Kramat/... in the center of Jakarta.

We'll think about saving exact settlement for our map objects (at least streets). We do not do it now cause we try to make our map files as small as possible.

**Comment by VMironiuk** [comment]
@tatiana-yan  Now it's clear, thanks for the response!
