### ISSUE TITLE
Provide a better service for interface translation

### ISSUE THREAD

**Issue by naoliv** [mapsme/omim#3810]
Please, is it possible to have a better and centralized service for the translation?
It's a hell to try to have more than one people translating it (dealing with branches, merging, etc)

**Comment by Zverik** [comment]
We have too few user-contributed translations to change our translation stack. Nearly all translations are done by paid professionals, since we are usually short on time, and there is 30 languages. Contributors wanting to update translations are usually okay with making pull requests, and if not, they can write to bugs@maps.me for us to fix error.
