### ISSUE TITLE
Error: using destination streets?

### ISSUE THREAD

**Issue by OSMmapper** [mapsme/omim#4861]
Why does mapsme uses vehicle=destination (or access=destination) streets for navigation who are closed for transit traffic?
Is it possible to use this streets only if the destination address is in this street?

https://wiki.openstreetmap.org/wiki/Key:access

**Comment by thany** [comment]
Closed roads would need an uplink, wouldn't it? Or would you expect maps.me to periodically download traffic information in addition to the maps? I'm not sure if such information is available publicly and freely. And I'm not sure that anything at all, downloaded in advance, will be up-to-date enough to work even slightly good.

**Comment by Zverik** [comment]
First, we are using the default OSRM profile for the routing at the moment, which also disregards `access=destination` tags. See [this route](http://www.openstreetmap.org/directions?engine=osrm_car&route=55.7621%2C37.6301%3B55.7593%2C37.6272#map=17/55.76065/37.62904&layers=N) for an example.

Second, restricting "destination" streets only to destination addresses is not a simple task, since such closed roads can form a quite large network.

We may revise our routing algorithm in the future to support destination streets, but for now we have to do with such imperfect routes.
