### ISSUE TITLE
Notes: Comments, hard to read.

### ISSUE THREAD

**Issue by AllroadsNL** [mapsme/omim#5332]
What is essential in a comment.

That is the comment of the user.

It is not easy to find the comment of the user, in a standard placed text.

The built up of these comments are wrong.

Example;
[876983](http://www.openstreetmap.org/note/876983)

The place has gone or never existed. This is an auto-generated note from MAPS.ME application: a user reports a POI that is visible on a map (which can be outdated), but cannot be found on the ground. User comments: "Existiert nicht" (OSM data version: 2017-01-19T15:17:02Z) #mapsme

This is annoying for the notes solvers.

[also on RSS feeds](http://resultmaps.neis-one.org/osm-notes-country-feed?c=Germany&a=opened)

What should be important and placed in front.

"Existiert nicht"
(blank between rule)
then the extra standard info, if needed. 
Mapsme info: and, and.

**Comment by Zverik** [comment]
We made this text long in anticipation that most users won't comment. We can change it if there is a better option. Alas, empty lines are removed by OSM API.

**Comment by utack** [comment]
Agree with OP  
The feed of notes is really hard to read currently, maybe push the user note to the front

**Comment by planemad** [comment]
Also please add a link to the original OSM object. In densely mapped areas, its not clear what object the user may have been referring to when reporting that its gone. eg. https://www.openstreetmap.org/note/836986

**Comment by AllroadsNL** [comment]
As a note solver, i like to know if the the note is made on the exact location or afterwards, notes should be made on the highest/deepest zoom level.
A picture is more reliable as a memory afterwards.
A little odd nobody respond to this. #5331
We can ask more effort from a note maker, then we do now.
And ask some questions.

**Comment by SB79** [comment]
I can only underline the importance of what @planemad already wrote: It is essential to name the object ID and version in the automatically generated OSM note. This enables OSM contributors to better react to notes places by MAPS.ME users.

Reason: When a MAPS.ME user labels a place as obsolete (= "does not exist anymore"), the app adds an OSM note to that location. However, the standard text of the note does not contain any ID nor version of the object to which the MAPS.ME user was referring to. There are at least two problematic scenarios:

(1) The OSM database and the MAPS.ME database on the smartphone of the user are out of sync. That can easily happen, if the object the MAPS.ME user is referring has been edited by OSM contributors since the last time the MAPS.ME app downloaded the map data. In such a case, the OSM contributors don't have any clue of what to do with the note (because the note refers to an old state of the database).

(2) The location of the node contains several OSM objects such that OSM contributors do not know which object the maps.me user was referring to.

I guess that this problematic behavior of the MAPS.ME app can be easily fixed. This would much benefit the OSM community and could lead to faster and better responses to map bug reports by the MAPS.ME users.

**Comment by Zverik** [comment]
Fixed in https://github.com/mapsme/omim/pull/6039, already live.
