### ISSUE TITLE
launching maps.me from external app

### ISSUE THREAD

**Issue by cordovapolymer** [mapsme/omim#5507]
Hi, I'd like to add maps.me to phonegap-launch-navigator cordova plugin, https://github.com/dpa99c/phonegap-launch-navigator#adding-support-for-more-apps
https://github.com/dpa99c/phonegap-launch-navigator#supported-parameters
Does maps.me support geo: URI scheme?

**Comment by Zverik** [comment]
Yes, it does.

**Comment by cordovapolymer** [comment]
Can you give some details on the support, or point me to a specific line in src?

**Comment by dpa99c** [comment]
Is it currently possible (using the v1 API URI scheme) to launch maps.me in routing mode (for both Android and iOS)?

From what I can see in the [iOS API examples](https://github.com/mapsme/api-ios) and [source code](https://github.com/mapsme/api-ios/blob/master/api/MapsWithMeAPI.m) it seems not.

If that's the case, I'll open a separate feature request issue, because it would be useful to be able to do this, and be able to specify additional parameters such as start location, transport mode, etc.

I'm interested because I would like to add support to my [phonegap-launch-navigator](https://github.com/dpa99c/phonegap-launch-navigator) Cordova plugin.

**Comment by cordovapolymer** [comment]
@deathbaba , @vng , @igrechuhin , @yunikkk , @rachytski, @ExMix . @bykoianko , @rokuz , @Zverik 
can someone give some details on this?

**Comment by deathbaba** [comment]
@burivuh and @VladiMihaylenko should know it.
Only few code changes are necessary to correctly support it.

**Comment by cordovapolymer** [comment]
@burivuh, @VladiMihaylenko BUMP!

**Comment by burivuh** [comment]
Hi!

We do have that. Docs & examples will be updated in the nearest future.

**Comment by cordovapolymer** [comment]
@burivuh , thanks, maybe you can give us a reference to the code lines?

**Comment by cordovapolymer** [comment]
@burivuh , any updates on this?

**Comment by cordovapolymer** [comment]
@burivuh , BUMP! Waiting for the examples!

**Comment by cordovapolymer** [comment]
https://github.com/mapsme/api-android/wiki/Deeplinks
