### ISSUE TITLE
Can't rotate the map a little bit

### ISSUE THREAD

**Issue by thany** [mapsme/omim#6101]
When I try to rotate the map a little bit, by say, 10 degrees, it snaps back to 0 degrees.

Snapping back is fine (albeit a bit unneccesary because a user can also just tap the compass button), but the threshold should be much lower.

**Comment by thany** [comment]
A duplicate of this issue was closed, apparently. All that happened was an explanation of what I'm experiencing.

That's just stating the problem again. This time, please actually fix it as well.

**Comment by rokuz** [comment]
Dear, thany!
Snapping back is a feature of our app as it was said in mentioned explanation. We develop our features for majority of users. We determine it statistically and by means of surveys. If you personally don't like it, well we regret. Since we are open-source app you have a chance to fix it by yourself for yourself, look at UserEventStream::CheckAutoRotate().

**Comment by thany** [comment]
Make it an option then

**Comment by thany** [comment]
No wait! Fix #4334 first please.

**Comment by thany** [comment]
Also don't​ just close the issue. Is it fixed? No. So the issue is open.

**Comment by rokuz** [comment]
Same for #4334. We do not consider these issues as bugs, so it will not be fixed. That's why issues have been closed.

**Comment by redmanmale** [comment]
Issue != bug.

**Comment by rokuz** [comment]
Ok, to be precise, we do not consider these issues as bugs neither as features. Actually it is a personal desire :) So there is no reason to store it opened.

**Comment by thany** [comment]
The more reason to make it an option.

#4334 is quite freaking blatantly a huge gaping bug, btw. Have you read it at all?
