### ISSUE TITLE
The German term for amenity=fountain should be 'Brunnen' instead of 'Springbrunnen'

### ISSUE THREAD

**Issue by SelfishSeahorse** [mapsme/omim#7085]
'Springbrunnen' is a fountain subtype where the water is jet into the air, but there are also other types of fountains without jet where the water is poured into a basin (e.g. [this one](https://en.wikipedia.org/wiki/Gerechtigkeitsbrunnen_(Bern))).

Edit: And another minor translation mistake: leisure=swimming_pool should be 'Schwimmbecken', not 'Schwimmbad'.

**Comment by FountainMapper** [comment]
Fixing this issue caused a problem (seen in maps.me Version 7.6.5-Google Datenversion 171117).
Now the POIs "fountain" and "water_well" are both displayed as "Brunnen". This affects showing a POI and as well ADDING a POI. I need to choose between "Brunnen" and "Brunnen". But which one is a fountain and which is a water_well?
I prefer to rename "Brunnen" (fountain!) back to "Springbrunnen".
Fountains are very common in South America. On my last bicycle trip I used maps.me to add a lot of them (and some thousand other POIs). In Peru, Bolivia and northern Chile every village and city has a main square, often with a fountain.

Below is the email I sent to bugs@maps.me before I was notified about this issue:
##############################################
[..]
since a few month the german localization has an issue. I guess the release six month ago was fine.

When I add a new POI I have the (german) word "Brunnen" twice in the list. These are two different objects and shall have different names!

Current maps.me version:
...
Brunnen (german) --> Water Well (english)
Brunnen (german) --> Fountain (english)
...

Older maps.me versions:
...
Brunnen (german) --> Water Well (english)
...
Springbrunnen (german) --> Fountain (english)
...

To reproduce: Change the keyboard language to german, add a POI, choose any position and check the list.

I guess this also affects when I select an exisiting POI on the map (same word for different objects).
[..]
##############################################

**Comment by SelfishSeahorse** [comment]
> Now the POIs "fountain" and "water_well" are both displayed as "Brunnen". This affects showing a POI and as well ADDING a POI. I need to choose between "Brunnen" and "Brunnen". But which one is a fountain and which is a water_well?

Sorry, I didn't think of that ...

> I prefer to rename "Brunnen" (fountain!) back to "Springbrunnen".

Maybe *Zierbrunnen* would be better, because – unlike *Springbrunnen* – this term doesn't exclude [Laufbrunnen](https://de.wikipedia.org/wiki/Laufbrunnen).

**Comment by FountainMapper** [comment]
I prefer "Springbrunnen". This word is used in "iD" and in "How to map"
http://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Dfountain
(I dont know the german description in other editors.)
I guess a "Laufbrunnen" should be mapped as a water_well, not a fountain, because it was/is used to take water from it.

**Comment by SelfishSeahorse** [comment]
Apparently these translations are imprecise.

The (approved) [definition](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfountain) of `amenity=fountain` is 'a fountain for cultural / decorational / recreational purposes'.

> I guess a "Laufbrunnen" should be mapped as a water_well, not a fountain [...]

No, `man_made=water_well` is defined as a 'structural facility created to access ground water from an *aquifer*'.

> [...] because it was/is used to take water from it.

As far as I know, all fountains were originally used to take water from it (for drinking and washing).

**Comment by FountainMapper** [comment]
Now we discuss in english the german translation of a term, implemented by russian(?) speaking developers.
For me its fine if YOU CHOOSE a correct term (as long as it not collides with already used terms like "Brunnen"). And maybe you could update the german translations in the OSM wiki to the approved english texts.

As far as I unterstand not all fountains were originally used to take water.
See https://de.wikipedia.org/wiki/Kohlmarktbrunnen
This one was rebuild at a slightly different position for decoration purpose in 1865.

Or see: https://en.wikipedia.org/wiki/King_Fahd%27s_Fountain
Operated with salt water. I guess every person approaching to wash something would be "rejected".

Also cities in central Europe are usually quite old. The may have started with fountains to take water from it. But is eastern China cities are build from scratch with a water distribution system. So fountains are only for decoration. Also settlements in northern Canada or southern Chile are quite young.

**Comment by SelfishSeahorse** [comment]
> As far as I unterstand not all fountains were originally used to take water.

You are right. I'm sorry, I was imprecise. What I wanted to say is that the function of fountains originally was to supply water, but now they have a decorational purpose, in contrast with water wells, of which the function still is to supply water.

> For me its fine if YOU CHOOSE a correct term

I don't want to choose, actually it's up to the developers of Maps.me to choose. :-) I just want to prevent that tags have different meanings in different regions. If someone has a better idea than *Zierbrunnen* I would be very happy.

**Comment by mpimenov** [comment]
> I don't want to choose, actually it's up to the developers of Maps.me to choose. :-)

We don't have a native German speaker here, so your discussion is likely going to be the main source for our eventual implementation.

That said, I'm still not sure about two things:
1. Is German OSM Wiki incomplete or incorrect on this part?
2. Do you have a proposal that would leave both of you (and, with luck, all German users of the application) satisfied?

**Comment by SelfishSeahorse** [comment]
Hi

The definition on the German OSM wiki page is incomplete as – unlike the English page – it excludes some type of fountains where the water isn't jet into the air but runs out of a pipe.

[I've just discussed this](https://wiki.openstreetmap.org/wiki/User_talk:Reneman#DE:Tag:amenity.3Dfountain) with two other German speaking mappers and they prefer *Springbrunnen* as short description (in the info box). However we'll improve the detailed description/summary.

Therefore I ask you to revert the German translation of `amenity=fountain` back to *Springbrunnen*. Please excuse the unnecessary efforts caused by my issue report.

**Comment by FountainMapper** [comment]
By the way: 
-I am a native German speaker
-Currently UNEMPLOYED computer scientist
-Main qualification for a job: my position in the maps.me ranking is 23 (with 3652 changes, not mapping addresses)
-Я понимаю по-русски чуть-чуть.
:)
