### ISSUE TITLE
allow adding local name for an existing object (currently many maps.me edits duplicate existing objects)

### ISSUE THREAD

**Issue by matkoniecz** [mapsme/omim#7969]
People using maps.me editor frequently make this type of mistake: adding place of worship node inside well tagged place of worship

https://www.openstreetmap.org/node/4418191189#map=19/50.04328/19.94993&layers=N

![selection_007](https://user-images.githubusercontent.com/899988/35157194-87cf4af8-fd33-11e7-8da9-4c55ecdf17f9.png)

it would be preferable to fix editor so it is making easier to add names in foreign languages to existing objects and/or block creating nodes duplicating existing objects.

**Comment by drkludge** [comment]
I've seen the same problem with iD, Potlatch, and Josm.

**Comment by matkoniecz** [comment]
In my region it is (in cases that I encoutered and fixed) almost always MAPS.ME.

JOSM discourages it by validator warnings.

**Comment by Zverik** [comment]
So a user sees a big 3D church with a prominent dot on which they can click. And they choose instead to go into a menu and click "Add a new object here", then adding a new church inside an existing one. If they didn't notice a big church on the map, I doubt they would notice a warning message.

I think the real issue here is that you cannot add a local name to an existing church.

**Comment by matkoniecz** [comment]
I updated issue title - it seems to explain reason why maps.me users keep creating duplicates.
