### ISSUE TITLE
Waterfall not a node of an existing waterway

### ISSUE THREAD

**Issue by cliffordsnow** [mapsme/omim#8327]
A first time user added 32 waterways using MAPS.ME. None of the new waterfalls were part of a stream or river. Usually placed a few meters from the existing waterway. Shouldn't the app expect the waterfall to be a node of an existing way. I can see an exception to an area with no stream or river. 

See [changeset 57247262](https://www.openstreetmap.org/changeset/57247262) for more info.

**Comment by burivuh** [comment]
@Zverik, can we do anything with that?

**Comment by Zverik** [comment]
Hi Clifford,

Thanks for raising this issue. I agree that waterfalls should be best mapped as nodes inside waterways. Alas, maps.me cannot add nodes inside existing geometry at the moment. We decided against mapping building entrances for that very reason, but with waterfalls, we think that allowing users add that information is more important than keeping their geometry perfect. Because waterfalls are important points of interest, their number is not too big, and when needed, mappers can easily fix the issue.

The only way to fix this for now is to forbid maps.me users from mapping waterfalls. I'm not sure it is a good way to go. As for plans regarding editing geometry, I don't think we can disclose that, but @burivuh can elaborate on that.
