### ISSUE TITLE
Street search in a village not working

### ISSUE THREAD

**Issue by Jurkis** [mapsme/omim#998]
I search for address: Senieji Trakai (it's a village), Trakų str. - no data found.
Senieji Trakai, Trakų str. nominatim does exist in openstreetmap.org.

**Comment by deathbaba** [comment]
When this feature was added into OSM?
May be it was added AFTER our maps version was generated. In this case you will find it after upcoming maps data update.

**Comment by Jurkis** [comment]
I'm not sure, but i think that it was always possible to search in OSM any street in any village.
I tested using latest official maps and http://direct.mapswithme.com/regular/daily/ (14 of dec).

**Comment by deathbaba** [comment]
Search query http://www.openstreetmap.org/search?query=Senieji%20Trakai#map=14/54.6052/24.9828 <http://www.openstreetmap.org/search?query=Senieji%20Trakai#map=14/54.6052/24.9828> shows only City Boundary, not city/village/town. We don’t display names for City Boundaries now, probably due to some rendering issues.

**Comment by Jurkis** [comment]
Now it's working (eg "Trakų 8 senieji").
